### ISSUE TITLE
Enhance profile editor UI/UX

### ISSUE THREAD

**Issue by rasoulMrz** [Utopia42-club/utopia42-web#6]
Double-check this dialog UI to see if enhancements are required

**Comment by aminabs** [comment]
Checked.
Minor ui improvements are nice to have.

Yet another discussion is required on the web/unity interoperability in order to make user fill seamless transition between unity and web. The profile dialog is an example. Also we may decide to open similar dialogs as an angular dialog instead of unity dialogs (not sure).

**Comment by aminabs** [comment]
The make NFT button does not work for me. It might be my bad.

**Comment by rasoulMrz** [comment]
> de to open simil

Profile Editor dialog in utopia-web is an angular dialog! (don't confuse with the LandProfile dialog in unity)
